# SPDX-License-Identifier: GPL-3.0-only
# Conky system panel. Does nothing until conky is installed; Alt+Shift+T picks a theme or Off.
exec sh ~/.config/conky/start.sh
bindsym $mod+Shift+t exec sh ~/.config/conky/switch.sh
