# SPDX-License-Identifier: GPL-3.0-only
# Notes scratchpad: Alt+` toggles a floating kitty running nvim; each new window is a new
# note (scratch.md, scratch-1.md, ...). See notes.sh.
# Alt+n is avoided on purpose: sway would swallow it before Herdr's prefix+alt+n.
for_window [app_id="notes-scratchpad"] floating enable, resize set 60 ppt 60 ppt, move position center, move scratchpad, scratchpad show
bindsym $mod+grave exec sh ~/.config/sway/notes.sh
