# SPDX-License-Identifier: GPL-3.0-only
# Notes scratchpad: Alt+` toggles a floating kitty running nvim on ~/notes/scratch.md.
# Alt+n is avoided on purpose: sway would swallow it before Herdr's prefix+alt+n.
for_window [app_id="notes-scratchpad"] floating enable, resize set 60 ppt 60 ppt, move position center, move scratchpad, scratchpad show
bindsym $mod+grave exec sh -c 'swaymsg "[app_id=notes-scratchpad] scratchpad show" || { mkdir -p ~/notes && exec kitty --class notes-scratchpad nvim ~/notes/scratch.md; }'
